### PR TITLE
Include a default SPDX License Identifier

### PR DESCRIPTION
**Pull request by nanexcool**

### CODE REVIEW

**Comment by transmissions11** [comment]
Forgive me if I'm missing something but why quote the license comment?

**Comment by transmissions11** [comment]
Also is unlicensed a good choice? Thought we wanted to go for something permissive

**Comment by transmissions11** [comment]
Also thoughts on defaulting to a permissive license?

**Comment by nanexcool** [comment]
> Forgive me if I'm missing something but why quote the license comment?

ah yeah, I think the quotes are not needed, I'll remove.

> Also thoughts on defaulting to a permissive or copyleft license?

I'm fine with anything. I'd default to MIT maybe, but anything is better than having to copy paste from the warning message :P

**Comment by transmissions11** [comment]
MIT sounds good. one thing idk about is technically DSTest is GPL... does that mean test files have to be GPL as well? i mean no one is gonna enforce that but should at least think about it if this is gonna be what the tool is recommending by default :p

**Comment by d-xo** [comment]
@nanexcool please change to GPL and I will merge :slightly_smiling_face:

**Comment by nanexcool** [comment]
> @nanexcool please change to GPL and I will merge 🙂

done!

**Comment by MrChico** [comment]
so agressive, I love it

**Pull request merged**
