### PR TITLE
seth: add Optimistic Ethereum and Arbitrum Support

### PR DESCRIPTION
**Pull request by rajivpo**
provide optimistic ethereum (mainnet and kovan)  and arbitrum (mainnet) support for `seth` and update relevant documentation

**How this has been tested**
- set `ETH_RPC_URL` to an to the relevant infura endpoint
- [x]  check that`seth chain` returns the correct chain
- [x] `seth chain-id` returns `10` (https://chainid.link/?network=optimism for verification)
- [x] `seth block-number` returned the latest block (check relevant explorer to confirm)
- [x] `seth block 0` returns the same info as making the infura call to `eth_getBlockByNumber` with params `["0x0", true]`

Could also add arbitrum rinkeby support, but i'm not aware of whether there is an etherscan api compatible explorer for it.

### CODE REVIEW

**Comment by transmissions11** [comment]
Can we get OE Kovan support too 🙏🙏

**Comment by rajivpo** [comment]
> Can we get OE Kovan support too 🙏🙏

anything else you would wanna see as part of this PR?

**Comment by transmissions11** [comment]
> > Can we get OE Kovan support too 🙏🙏
> 
> 
> 
> anything else you would wanna see as part of this PR?

Arbitrum? xD

**Comment by transmissions11** [comment]
There's an arbitrum testnet too right?

**Comment by rajivpo** [comment]
> There's an arbitrum testnet too right?

Yeah  I can add Arbitrum rinkeby but not sure what the corresponding etherscan for that is.

**Comment by transmissions11** [comment]
> not sure what the corresponding etherscan for that is.

Oo yeah idk either maybe save for a future PR 😅

**Review by gakonst — APPROVED** [review]

**Pull request merged**
