### PR TITLE
enable hevm traces on passing unit tests

### PR DESCRIPTION
**Pull request by rainbreak**
With this change:

- `dapp test`: shows traces for failing tests
- `dapp test --verbose`: also show traces for passing tests

Also, emit raw event data in the case of anonymous events (e.g. ds-note).

@gbalabasquer @nanexcool :)

### CODE REVIEW

**Comment by nanexcool** [comment]
Works great! I'd modify the Changelog and up the version since @mbrock has been pretty consistent with that

**Comment by asymmetric** [comment]
I guess we should upgrade both the `dapp` and `hevm` changelogs?

**Comment by rainbreak** [comment]
dapp has a changelog?

**Comment by nanexcool** [comment]
@asymmetric I'm merging this in an hour. We can merge the `dapp` Changelog as well

**Pull request merged**
