### PR TITLE
ethsign: factor out repetitions

### PR DESCRIPTION
**Pull request by MrChico**
Just a minor clean up. Addresses (part of) https://github.com/dapphub/dapptools/issues/121

### CODE REVIEW

**Comment by MrChico** [comment]
cc @nanexcool

**Comment by asymmetric** [comment]
Have you tested manually that it works as intended?

We should have unit tests for this obviously.

**Comment by MrChico** [comment]
Tried the error propagation and the actual signing with some files in `keystore` which works. Did not try with any hardware wallets, but it should not be a problem

**Comment by nanexcool** [comment]
This is not working for me on Ubuntu 18 with a Ledger. Then again... neither is master, so will have to investigate further.

**Comment by nanexcool** [comment]
I'd suggest merging this, then figure out why Ledger doesn't work. Was looking at go-ethereum code yesterday, and I'm pretty sure they straight up do not support message signing using Ledger. 

https://github.com/ethereum/go-ethereum/blob/7c91038bff21b9085f61108d75716e2d57cdca8b/accounts/usbwallet/wallet.go#L514

**Pull request merged**
