### PR TITLE
dapp: Load .dapprc before setting DAPP_REMAPPINGS

### PR DESCRIPTION
**Pull request by TransmissionsDev**
Fixes https://github.com/dapphub/dapptools/issues/674

Context: https://github.com/dapphub/dapptools/issues/674#issuecomment-870982337

### CODE REVIEW

**Comment by TransmissionsDev** [comment]
Can we create a new release of hevm once this PR is merged so installing dapptools will use this latest version? :p

**Comment by TransmissionsDev** [comment]
Can you guys also make a release in this repo once this gets merged so the dapptools installer will use this latest dapp version (will also add invariant support I believe)? 😅

**Comment by d-xo** [comment]
Thanks! I'm just waiting for the `ffi` pr to land before I cut a new release. Hopefully in the next day or two.

**Comment by TransmissionsDev** [comment]
> Thanks! I'm just waiting for the `ffi` pr to land before I cut a new release. Hopefully in the next day or two.

yay!

**Pull request merged**
