### PR TITLE
🖖 add solc `0.8.16` and keep dapptools up-to-date

### PR DESCRIPTION
**Pull request by pcaversaccio**
## Description

Add support for solc `0.8.16`. The content was generated using `$ ./nix/make-solc-static.sh`.

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [x] updated the changelog

Cc: @d-xo @cleanunicorn

### CODE REVIEW

**Comment by pcaversaccio** [comment]
reminder @d-xo @cleanunicorn

**Comment by cleanunicorn** [comment]
@pcaversaccio LGTM. However, I don't have permission to merge the branch.

Have you considered migrating to https://github.com/foundry-rs/foundry ?

**Comment by pcaversaccio** [comment]
@cleanunicorn yeah, have been using foundry for a while already. I just feel I want to keep dapptools supported until last version of solc 0.8 😎.

**Comment by pcaversaccio** [comment]
closed in favour of https://github.com/dapphub/dapptools/pull/960.

**Pull request closed without merging**
