### PR TITLE
Replace Travis with GitHub actions

### PR DESCRIPTION
**Pull request by asymmetric**
Nix support on Travis is currently [broken](https://github.com/travis-ci/travis-build/pull/1833) due to some issues with the macOS builders, that prevent updating the Nix version.

Moving to GitHub actions, apart from fixing that (temporary?) issue, also gives us the benefit that there's more Nix people working on actions than on Travis, so hopefully things won't break again in the future.

Also:

- centralized secret management
- better integration with GH (d'uh)

### Outputs are not pushed to Cachix for external PRs (cfr. [docs](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories))

:heavy_check_mark: This works as expected because secrets are not available to builders started from forks, so no push.

### Some build artifacts seem to not be getting pushed

Specifically, hevm and geth-unlimited (oof!). The main problem is if this forced everyone who installs dapptools to have to build them locally. Needs to be investigated further.

### Outputs from all branches are built

So anybody who has write access to this repo can push to Cachix. @xwvvvvwx suggested protecting master, but I haven't fully investigated if this would actually help.

We could also restrict pushes to Cachix to builds on the master branch, whereas tests would run for each commit on each branch.

### CODE REVIEW

**Comment by xwvvvvwx** [comment]
Nice!

I see `/nix/store/ajrrkivdfvp8dp4vdg5hp1h5hblmanc9-binutils-2.31.1/bin/ranlib: dist/build/libHSjays-1.20171121-HSYOMgNe8gwI2Ydn1RXAdw-ghc8.6.5.a: No space left on device` on the linux build atm?

**Comment by asymmetric** [comment]
Can you link to where you see it?

**Comment by xwvvvvwx** [comment]
https://github.com/dapphub/dapptools/pull/402/checks?check_run_id=784702108#step:5:3062

**Comment by asymmetric** [comment]
Seems like it's due to the partition being 14GB, cfr. https://github.com/actions/virtual-environments/issues/709#issuecomment-627265622.

Let's see if restarting the job fixes it, since it won't need to rebuild as much stuff.

**Comment by asymmetric** [comment]
Otherwise we might have to manually remove stuff from the FS :(

Also: not sure why the `ubuntu-latest` built is shown twice.

**Comment by asymmetric** [comment]
> Let's see if restarting the job fixes it, since it won't need to rebuild as much stuff.

Wait that was dumb, it won't push anything to the cache because we haven't configured the private key.

**Comment by xwvvvvwx** [comment]
If we keep running into these kind of resource limits on the free services, maybe we should think about migrating to [hercules](https://hercules-ci.com/) on a hetzner box (maybe even just on the `dapp.ci` box?)

**Comment by asymmetric** [comment]
Space problems should be solved for now.

**Comment by asymmetric** [comment]
Seems like push to cachix isn't happening (anymore) though.

**Comment by asymmetric** [comment]
PTALA.

**Comment by asymmetric** [comment]
Closing this, and reopening a PR on this fork.

**Pull request closed without merging**
