### PR TITLE
Hevm39

### PR DESCRIPTION
**Pull request by MrChico**
Mainly to have something to fall back to before the release that will come with #353

### CODE REVIEW

**Comment by asymmetric** [comment]
So this closes #421?

**Comment by asymmetric** [comment]
Also, IIUC this means using < 0.6.x in tests won't work anymore?

In general, it seems there is something we should document about this magic version number in hevm and how/when it matters for users.

**Comment by MrChico** [comment]
> So this closes #421?

It's based on top of it, so it can replace it or follow it

**Comment by MrChico** [comment]
> Also, IIUC this means using < 0.6.x in tests won't work anymore?

It means using `< 0.6.x` one will need to provide `dapp --use solc:0.5.2` or whatever to use with older versions. Default will be `0.6.7`

**Comment by asymmetric** [comment]
So e.g. `dapp --use solc.0.5.2 test`?

**Comment by MrChico** [comment]
exactly

**Pull request merged**
