### PR TITLE
hevm: tty memory pager - fixes #164

### LINKED ISSUE #164: hevm: scrollable memory view
AFAIK it's not currently possible to scroll the memory view.

/cc @rainbreak

### PR DESCRIPTION
**Pull request by desaperados**
added key-bindings help (h)
added memory pager view (M)
moved event handlers to a function

### CODE REVIEW

**Comment by rainbreak** [comment]
Does the pager persist the location of the view when toggled? So that in a large view I don't lose my scrolling position.

**Comment by rainbreak** [comment]
Hmm good point. I was thinking of the basic case of within a frame. In a new frame it should reset, but when you pop back to a frame it could persist. However that's likely be quite annoying to implement?

**Comment by desaperados** [comment]
This sounds like an argument for implementing scrolling inside the memory pane itself rather than an expanded view where scrolling position becomes an issue. I was thinking that using an expanded view would be cleaner, and allow sharing of event handlers etc. but maintaining context could actually be less problematic.

**Comment by desaperados** [comment]
I've pushed a version which implements scrolling in the memory pane itself - if we later find that that we later need scrolling in other panes can do that too - would just need to implement some kind of scrolling context switcher.

**Comment by rainbreak** [comment]
Yes, let's play around with it and see. This is a huge improvement :)

**Pull request merged**
