### PR TITLE
Update hevm deps and nixpkgs to 21.05

### PR DESCRIPTION
**Pull request by arcz**
Update some deps, especially `base16-bytestring` since its API changed and broke hevm in nixpkgs which I unbroke a while ago. Not sure if it's the problem on my end but I had to fallback to static solc in `overlay.nix` because none of versions are building on macOS.

### CODE REVIEW

**Comment by MrChico** [comment]
Thanks! Didn't know there was a new release. Triggered ci

**Comment by xwvvvvwx** [comment]
looks like `dapp` builds are failing due to some new shellcheck features...

**Comment by arcz** [comment]
Should be fixed now

**Comment by arcz** [comment]
@MrChico Not sure what happened to the ubuntu build, looks like a race condition?

**Comment by xwvvvvwx** [comment]
reran CI and it's still failing so I guess it's not a race?

**Comment by arcz** [comment]
yeah, I looked at the wrong place. I'm investigating this

**Comment by xwvvvvwx** [comment]
wondering if bumping the sleep 90s to like 10 mins or something might help?

Perhaps nix needs to build a new patched geth version since we've bumped nixpkgs and that's taking more than 90s?

**Comment by arcz** [comment]
bumped to 10 mins, let's see

**Comment by xwvvvvwx** [comment]
It's passing!

Big thanks for all the work @arcz, very much appreciated 💖

**Pull request merged**
