### PR TITLE
Add `seth basefee` command

### PR DESCRIPTION
**Pull request by nanexcool**

### CODE REVIEW

**Comment by d-xo** [comment]
Can you also add a little entry on the readme for this command please?

**Comment by TransmissionsDev** [comment]
> > Can you also add a little entry on the readme for this command please?
> 
> 
> 
> Done! Let me know if it's ok :)

Gotta add a link at the bottom or the table of contents entry won't fit in 😅

**Comment by nanexcool** [comment]
> > > Can you also add a little entry on the readme for this command please?
> > 
> > 
> > Done! Let me know if it's ok :)
> 
> Gotta add a link at the bottom or the table of contents entry won't fit in 😅

done! damn, I need to write a PR checklist, always forgetting something :P

**Review by MrChico — APPROVED** [review]

**Comment by MrChico** [comment]
Thank you @nanexcool !

**Pull request merged**
