### PR TITLE
Release candidate

### PR DESCRIPTION
**Pull request by jennypollack**
## Checklist

- [ ] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

**Comment by d-xo** [comment]
lgtm. As we discussed in chat, I would probably merge all the commits into one, and then tag that same commit four times to avoid the situation we had last release with inconcistent version numbers in the release picked by the dapptools installer.

**Comment by d-xo** [comment]
lgtm. As we discussed in chat, I would probably merge all the commits into one, and then tag that same commit four times to avoid the situation we had last release with inconcistent version numbers in the release picked by the dapptools installer.

**Comment by MrChico** [comment]
why multiple tags? Wouldn't that cause multiple releases?

**Comment by d-xo** [comment]
Don't we normally do one release for each tool?

**Comment by MrChico** [comment]
there's not so much point in doing that

**Comment by d-xo** [comment]
sure, I agree, but if we want to have one version for all tools we need to implement a new version numbering scheme and I don't think it's worth blocking this release to figure that out, or did you have something else in mind?

**Comment by MrChico** [comment]
no, I don't think we need to change version numbers either. What I'm saying is that right now we are usually bumping all of the numbers at the same time, making one tag, and therefore one release. At least thats what I've been doing. The install scripts always use the latest release anyway, so it's not like ppl are gonna get the different tools from the different releases

**Comment by d-xo** [comment]
Ah I see what you mean now. Actually I always tagged each version of each tool separately when I cut a release, but I guess a single tag is fine too 🤷‍♀️

**Pull request merged**
