### PR TITLE
hevm: default to z3 for smt solving

### PR DESCRIPTION
**Pull request by d-xo**
We're still hitting this unfortunate sbv issue :(

https://github.com/dapphub/dapptools/issues/671

### CODE REVIEW

**Review by MrChico — APPROVED** [review]

**Comment by MrChico** [comment]
Oops, didnt mean to approve as ci is failing

**Comment by MrChico** [comment]
Consider my approval revoked

**Comment by MrChico** [comment]
:(

**Comment by d-xo** [comment]
tests didn't pass consistently twith z3 ill I bumped the timeout to 10mins.... :cry:

**Comment by MrChico** [comment]
kind of frustrating. We could also remove the intensive tests from dapp tests, I'm guessing it's distributivity and prime factorization

**Comment by d-xo** [comment]
yeah, I'm not really worried about the impact on ci, and I would prefer to keep those tests since I think they're good and interesting ones. I'm just sad about the performance impact for end users. I don't see much of a choice at the moment though given the issues with cvc4.

**Pull request merged**
