### PR TITLE
Nix solidity package: call solc just one and extract all the files af…

### PR DESCRIPTION
**Pull request by gbalabasquer**
…ter if needed

Co-authored-by: Christopher Fredén <me@icetan.org>

### CODE REVIEW

**Comment by MrChico** [comment]
Can you explain usage of this technology?

**Comment by icetan** [comment]
The changes intend to make the nix function `solidityPackage` behave more closely to `dapp build`.

Before `solc` was run twice to extract separate files for `.bin` etc. but is now using the same method as `dapp build --extract`.

**Comment by MrChico** [comment]
Yeah, the changes themselves make sense. I'm just wondering where `solidityPackage` is used. Is this part of `dapp2nix` or something similar?

**Comment by icetan** [comment]
Not really sure where it's used except in `dapp2nix` and here https://github.com/dapphub/ds-test/blob/master/default.nix#L1

I had a thought about copying `solidityPackage` to `dapp2nix` to be more flexible but I guess if it is to be compatible with `dapp` it should be housed along side it.

**Comment by MrChico** [comment]
as we discussed before, I think a `--dapp2nix` flag to `dapp` which assumes that everything is being done through nix is still a good idea, and I'd be happy to accept changes into dapptools that explores this

**Pull request merged**
