### PR TITLE
Changelog fixes

### PR DESCRIPTION
**Pull request by transmissions11**

### CODE REVIEW

**Comment by MrChico** [comment]
lets make a seth release

**Comment by transmissions11** [comment]
Can we get one for hevm too? The async stuff was breaking for the Maker peeps right? others could run into that as well if they're not pulling from master

**Comment by MrChico** [comment]
since this is a monorepo we're actually always releasing everything when we do a release. So yeah, time for a dapptools release

**Comment by transmissions11** [comment]
oh yup

https://github.com/dapphub/dapp-tools/blob/c8628ba28d2db66c881ab58e68ce64c9ebf4fd57/install#L21

**Pull request merged**
