### PR TITLE
solc: don't build 4.18 on osx

### PR DESCRIPTION
**Pull request by xwvvvvwx**
4.18 dosn't build on osx....

### CODE REVIEW

**Comment by MrChico** [comment]
It does for me? I tried it locally and it does, anyway

**Comment by MrChico** [comment]
But its strange that it doesnt on ci

**Comment by rainbreak** [comment]
Can you build the other 0.4.x that are marked as not compiling?

**Comment by MrChico** [comment]
this change was a noop, because solc0.4.18 is not in `x86_64-linux` but in `unreleased`

**Comment by xwvvvvwx** [comment]
oh, shit. working on a fix....

**Comment by MrChico** [comment]
I got it in #441

**Comment by xwvvvvwx** [comment]
:pray:

**Pull request merged**
